// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"EventScripts","status":true,"description":"","parameters":{}},
{"name":"Programmable","status":true,"description":"","parameters":{}}
];
